### ISSUE TITLE
[DVMod] Initial Design Todo on View Modifier Pattern

### ISSUE THREAD

**Issue by lilingxi01** [taci-tech/defined-elements-swiftui#14]
# Built-ins DVModifier (transferred from #12)

- [x] Preset Modifier
- [ ] Dock Modifier (I forget what I wanted to make in this "dock")
- [x] Background Modifier
- [x] Background Pattern Modifier
- [x] Border Modifier
- [x] Border Pattern Modifier
- [ ] Frame Size Pattern Modifier **_(Pending to be decided if we really need it)_**
- [ ] Dynamic Frame Size Modifier
- [x] Content Color Modifier
- [x] Content Color Pattern Modifier

# Move to next release
The unfinished parts have already been moved to the next release: #25
